[package]
name = "remail-ui"
version = "0.1.0"
authors = ["Lucas Vieira <vieiralucas4@gmail.com>"]
edition = "2024"

[dependencies]
dioxus = { version = "0.6.0", features = ["router"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
